name: deploy-develop-heroku CI

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run : echo "needs build test"
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        if: github.ref == 'refs/heads/develop'
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_DEVELOP}}
        if: github.ref == 'refs/heads/main'
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_MAIN}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        remote_branch: master
